/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as DimensionesRouteImport } from './routes/dimensiones'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ParticipaRouteImport } from './routes/participa'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as DimensionesIndexRouteImport } from './routes/dimensiones.index'
import { Route as DimensionesSlugRouteImport } from './routes/dimensiones.$slug'
import { Route as DocumentosIndexRouteImport } from './routes/documentos.index'
import { Route as DocumentosCategoriaRouteImport } from './routes/documentos.$categoria'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as ProyectoIndexRouteImport } from './routes/proyecto.index'
import { Route as ProyectoSlugRouteImport } from './routes/proyecto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionesRoute = DimensionesRouteImport.update({
  id: '/dimensiones',
  path: '/dimensiones',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipaRoute = ParticipaRouteImport.update({
  id: '/participa',
  path: '/participa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionesIndexRoute = DimensionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DimensionesRoute,
} as any)
const DimensionesSlugRoute = DimensionesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DimensionesRoute,
} as any)
const DocumentosIndexRoute = DocumentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentosRoute,
} as any)
const DocumentosCategoriaRoute = DocumentosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => DocumentosRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const ProyectoIndexRoute = ProyectoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyectoRoute,
} as any)
const ProyectoSlugRoute = ProyectoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProyectoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/dimensiones': typeof DimensionesRouteWithChildren
  '/documentos': typeof DocumentosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/participa': typeof ParticipaRoute
  '/proyecto': typeof ProyectoRouteWithChildren
  '/dimensiones/$slug': typeof DimensionesSlugRoute
  '/documentos/$categoria': typeof DocumentosCategoriaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/proyecto/$slug': typeof ProyectoSlugRoute
  '/dimensiones/': typeof DimensionesIndexRoute
  '/documentos/': typeof DocumentosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/proyecto/': typeof ProyectoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/participa': typeof ParticipaRoute
  '/dimensiones/$slug': typeof DimensionesSlugRoute
  '/documentos/$categoria': typeof DocumentosCategoriaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/proyecto/$slug': typeof ProyectoSlugRoute
  '/dimensiones': typeof DimensionesIndexRoute
  '/documentos': typeof DocumentosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/proyecto': typeof ProyectoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/dimensiones': typeof DimensionesRouteWithChildren
  '/documentos': typeof DocumentosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/participa': typeof ParticipaRoute
  '/proyecto': typeof ProyectoRouteWithChildren
  '/dimensiones/$slug': typeof DimensionesSlugRoute
  '/documentos/$categoria': typeof DocumentosCategoriaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/proyecto/$slug': typeof ProyectoSlugRoute
  '/dimensiones/': typeof DimensionesIndexRoute
  '/documentos/': typeof DocumentosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/proyecto/': typeof ProyectoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/dimensiones'
    | '/documentos'
    | '/noticias'
    | '/participa'
    | '/proyecto'
    | '/dimensiones/$slug'
    | '/documentos/$categoria'
    | '/noticias/$slug'
    | '/proyecto/$slug'
    | '/dimensiones/'
    | '/documentos/'
    | '/noticias/'
    | '/proyecto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/participa'
    | '/dimensiones/$slug'
    | '/documentos/$categoria'
    | '/noticias/$slug'
    | '/proyecto/$slug'
    | '/dimensiones'
    | '/documentos'
    | '/noticias'
    | '/proyecto'
  id:
    | '__root__'
    | '/'
    | '/contactos'
    | '/dimensiones'
    | '/documentos'
    | '/noticias'
    | '/participa'
    | '/proyecto'
    | '/dimensiones/$slug'
    | '/documentos/$categoria'
    | '/noticias/$slug'
    | '/proyecto/$slug'
    | '/dimensiones/'
    | '/documentos/'
    | '/noticias/'
    | '/proyecto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  DimensionesRoute: typeof DimensionesRouteWithChildren
  DocumentosRoute: typeof DocumentosRouteWithChildren
  NoticiasRoute: typeof NoticiasRouteWithChildren
  ParticipaRoute: typeof ParticipaRoute
  ProyectoRoute: typeof ProyectoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensiones': {
      id: '/dimensiones'
      path: '/dimensiones'
      fullPath: '/dimensiones'
      preLoaderRoute: typeof DimensionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participa': {
      id: '/participa'
      path: '/participa'
      fullPath: '/participa'
      preLoaderRoute: typeof ParticipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensiones/': {
      id: '/dimensiones/'
      path: '/'
      fullPath: '/dimensiones/'
      preLoaderRoute: typeof DimensionesIndexRouteImport
      parentRoute: typeof DimensionesRoute
    }
    '/dimensiones/$slug': {
      id: '/dimensiones/$slug'
      path: '/$slug'
      fullPath: '/dimensiones/$slug'
      preLoaderRoute: typeof DimensionesSlugRouteImport
      parentRoute: typeof DimensionesRoute
    }
    '/documentos/': {
      id: '/documentos/'
      path: '/'
      fullPath: '/documentos/'
      preLoaderRoute: typeof DocumentosIndexRouteImport
      parentRoute: typeof DocumentosRoute
    }
    '/documentos/$categoria': {
      id: '/documentos/$categoria'
      path: '/$categoria'
      fullPath: '/documentos/$categoria'
      preLoaderRoute: typeof DocumentosCategoriaRouteImport
      parentRoute: typeof DocumentosRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/proyecto/': {
      id: '/proyecto/'
      path: '/'
      fullPath: '/proyecto/'
      preLoaderRoute: typeof ProyectoIndexRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/$slug': {
      id: '/proyecto/$slug'
      path: '/$slug'
      fullPath: '/proyecto/$slug'
      preLoaderRoute: typeof ProyectoSlugRouteImport
      parentRoute: typeof ProyectoRoute
    }
  }
}

interface DimensionesRouteChildren {
  DimensionesSlugRoute: typeof DimensionesSlugRoute
  DimensionesIndexRoute: typeof DimensionesIndexRoute
}

const DimensionesRouteChildren: DimensionesRouteChildren = {
  DimensionesSlugRoute: DimensionesSlugRoute,
  DimensionesIndexRoute: DimensionesIndexRoute,
}

const DimensionesRouteWithChildren = DimensionesRoute._addFileChildren(
  DimensionesRouteChildren,
)

interface DocumentosRouteChildren {
  DocumentosCategoriaRoute: typeof DocumentosCategoriaRoute
  DocumentosIndexRoute: typeof DocumentosIndexRoute
}

const DocumentosRouteChildren: DocumentosRouteChildren = {
  DocumentosCategoriaRoute: DocumentosCategoriaRoute,
  DocumentosIndexRoute: DocumentosIndexRoute,
}

const DocumentosRouteWithChildren = DocumentosRoute._addFileChildren(
  DocumentosRouteChildren,
)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface ProyectoRouteChildren {
  ProyectoSlugRoute: typeof ProyectoSlugRoute
  ProyectoIndexRoute: typeof ProyectoIndexRoute
}

const ProyectoRouteChildren: ProyectoRouteChildren = {
  ProyectoSlugRoute: ProyectoSlugRoute,
  ProyectoIndexRoute: ProyectoIndexRoute,
}

const ProyectoRouteWithChildren = ProyectoRoute._addFileChildren(
  ProyectoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  DimensionesRoute: DimensionesRouteWithChildren,
  DocumentosRoute: DocumentosRouteWithChildren,
  NoticiasRoute: NoticiasRouteWithChildren,
  ParticipaRoute: ParticipaRoute,
  ProyectoRoute: ProyectoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
