services:
  - type: web
    name: hqp2050-api
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma db push --schema prisma/schema.prisma --accept-data-loss && npx prisma db seed --schema prisma/schema.prisma && node dist/main.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGINS
        value: https://*.vercel.app
      - key: NODE_ENV
        value: production